### ISSUE TITLE
error when calling findNftsByCreator

### ISSUE THREAD

**Issue by pawy** [metaplex-foundation/js-next#47]
Hi

I get the following error when I call this two lines:
    const creator = new PublicKey("D9vTmH4hDS66L54dHit7keVWwtEJuyfFG3Ey5hHJRXHH")
    const nfts = await metaplex.nfts().findNftsByCreator(creator);

Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "fda19491-5acf-4adf-8dce-899014858bab" }

Same for findNftsByCandyMachine().

findNftByMint() on the other hand works fine.

Am I doing it wrong?

**Comment by pawy** [comment]
Thanks, so you are using getProgramAccount as well. I was using it before with genesysgo and it gives me this error since the latest RPC update.
Error: 403 Forbidden: Call type exceeds Solana 1.9.13 version limit for max account size.

However the only working rpc with this seems to be quiknode as used in https://magiceden.io/mintlist-tool
All other ways to get a list of mints I found, are no longer working.

**Comment by lorisleiva** [comment]
Yes, the default implementations are using `getProgramAccount` to fetch NFTs in bulk. This can be changed by plugins to retrieve NFTs in a different way — such as NFT indexers.

I'll close this since this is a limitation of `getProgramAccount` but I'll make sure to add some better warning/error handling to let developers know what's happening. 🙂
